# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#home_slider"
  weight = 1

[[main]]
  name = "Why KubeEdge"
  url = "#why-kubeedge"
  weight = 2

[[main]]
  name = "Documentation"
  url = "https://docs.kubeedge.io"
  weight = 3

[[main]]
  name = "Blog"
  url = "blog/"
  weight = 4

[[main]]
  name = "Downloads"
  url = "https://github.com/kubeedge/kubeedge/releases"
  weight = 5


# Right Menu
[[main_right]]
  name = "<i class=\"fab fa-github-alt\" style=\"color: #333; font-size: 1rem; line-height: 1.25\"></i>"
  post = ""
  url = "https://github.com/kubeedge/kubeedge"
  weight = 10

[[main_right]]
  name = "<i class=\"fab fa-twitter\" style=\"color: #55acee; font-size: 1rem; line-height: 1.25\"></i>"
  post = ""
  url = "https://twitter.com/KubeEdge"
  weight = 20

[[main_right]]
  name = "<i class=\"fab fa-slack\" style=\"color: #55acee; font-size: 1rem; line-height: 1.25\"></i>"
  post = ""
  url = "https://join.slack.com/t/kubeedge/shared_invite/enQtNjc0MTg2NTg2MTk0LWJmOTBmOGRkZWNhMTVkNGU1ZjkwNDY4MTY4YTAwNDAyMjRkMjdlMjIzYmMxODY1NGZjYzc4MWM5YmIxZjU1ZDI"
  weight = 30
  
# Documentation 

[[docs]]
  name = "Welcome"
  weight = 5
  identifier = "welcome"

[[docs]]
  name = "Setup"
  weight = 10
  identifier = "setup"

[[docs]]
  name = "Configuration"
  weight = 15
  identifier = "configuration"

[[docs]]
  name = "General Component"
  weight = 20
  identifier = "general component"

[[docs]]
  name = "Cloud Component"
  weight = 25
  identifier = "cloud component"

[[docs]]
  name = "Edge Component"
  weight = 30
  identifier = "edge component"

[[docs]]
  name = "EdgeSite"
  weight = 35
  identifier = "edgesite"

[[docs]]
  name = "Mapper"
  weight = 40
  identifier = "mapper"

[[docs]]
  name = "Contributing"
  weight = 45
  identifier = "contributing"

[[docs]]
  name = "Developer Guide"
  weight = 50
  identifier = "developer guide"
